### PR TITLE
Deploy6

### PR DESCRIPTION
**Pull request by johngrantuk**
- Update to deploy6
- Use snapshot method instead of fork start/stop for sequential swap tests
- Skip swap tests with join/exit path as these pools are not seeded yet because of some issues. #351

### CODE REVIEW

**Review by MattPereira — COMMENTED** [review]
Ran a `pnpm lint` locally that exited with errors not related to this PR. it just wants a trailing comma for the import, but its interesting that the checks pass in the remote environment :thinking: 

image

**Review by brunoguerios — APPROVED** [review]
LGTM ✅

**Review by MattPereira — APPROVED** [review]
Looking good with that sweet new snapshot method :sunglasses: 

I'll get started on updating scaffold to deploy6 after this is merged :rocket:

**Comment by johngrantuk** [comment]
> Ran a `pnpm lint` locally that exited with errors not related to this PR. it just wants a trailing comma for the import, but its interesting that the checks pass in the remote environment 🤔
> 
> image

That is strange, I've just pushed the fix but haven't taken the time to figure out why it didn't stop the CI!

**Pull request merged**
